
import jsPDF from "jspdf";

const imageToDataURL = (url) =>
  new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";

    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;

      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);

      resolve(canvas.toDataURL("image/png"));
    };

    img.onerror = reject;
    img.src = url;
  });

// ---------------------------------------------------------------------------
// Derived report fields (Report ID, Risk Level, AI Model name).
// These aren't produced by the backend today, so they're computed here from
// the existing `result` data. Swap generateReportId() for a backend-issued
// ID if/when you want true sequential numbering.
// ---------------------------------------------------------------------------
const generateReportId = () => {
  const now = new Date();
  const datePart = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(
    2,
    "0"
  )}${String(now.getDate()).padStart(2, "0")}`;
  const randomPart = String(Math.floor(Math.random() * 9000) + 1000);
  return `NSAI-${datePart}-${randomPart}`;
};

const getRiskLevel = (isCKD, confidence) => {
  if (!isCKD) return "Low";
  if (confidence >= 85) return "High";
  if (confidence >= 60) return "Moderate";
  return "Uncertain";
};

const AI_MODEL_NAME = "CNN (Convolutional Neural Network) v1.0";

// ---------------------------------------------------------------------------
// Shared drawing helpers
// ---------------------------------------------------------------------------
const drawHeaderBanner = (pdf, title, subtitle) => {
  pdf.setFillColor(21, 101, 192); // medical blue
  pdf.rect(0, 0, 210, 32, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.text(title, 20, 17);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(subtitle, 20, 25);

  pdf.setTextColor(0, 0, 0);
};

// Footer. `showDate` toggles the "Generated on" line (page 2 only, per spec).
const drawFooter = (pdf, pageLabel, showDate, generatedAt) => {
  pdf.setDrawColor(180);
  pdf.line(20, 283, 190, 283);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(110, 110, 110);

  pdf.text("Generated by NephroScan AI v1.0", 20, 289);
  if (showDate) {
    pdf.text(`Generated on: ${generatedAt}`, 20, 294);
  }

  pdf.text(pageLabel, 190, 289, { align: "right" });
  pdf.text(
    "Explainable AI for Chronic Kidney Disease Detection",
    190,
    294,
    { align: "right" }
  );

  pdf.setTextColor(0, 0, 0);
};

// Bordered card with a bold blue title — used for every "card/table" section
const drawCard = (pdf, x, y, w, h, title) => {
  pdf.setDrawColor(200);
  pdf.setFillColor(246, 248, 251);
  pdf.roundedRect(x, y, w, h, 2, 2, "FD");

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.setTextColor(21, 101, 192);
  pdf.text(title, x + 5, y + 8);
  pdf.setTextColor(0, 0, 0);
};

// Small colored dot + text line, used instead of emoji (✔ / ⚠) since the
// standard PDF fonts jsPDF ships with don't reliably render emoji/symbol
// glyphs — a drawn dot keeps the same "status at a glance" effect safely.
const drawBulletLine = (pdf, x, y, text, color) => {
  pdf.setFillColor(...color);
  pdf.circle(x, y - 1.3, 1.1, "F");
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10.5);
  pdf.setTextColor(0, 0, 0);
  pdf.text(text, x + 5, y);
};

export const generatePDF = async ({
  patient,
  result,
  image,
  gradcam,
  fileName,
}) => {
  const pdf = new jsPDF("p", "mm", "a4");
  const isCKD = result.prediction === "CKD";
  const riskLevel = getRiskLevel(isCKD, result.confidence);
  const reportId = generateReportId();
  const generatedAt = new Date().toLocaleString();

  const statusColor = isCKD ? [198, 40, 40] : [46, 125, 50];
  const statusBg = isCKD ? [253, 235, 235] : [232, 245, 233];
  const statusLabel = isCKD ? "CHRONIC KIDNEY DISEASE" : "NORMAL";

  // =========================================================================
  // PAGE 1 — Cover page
  // =========================================================================
  drawHeaderBanner(
    pdf,
    "NephroScan AI",
    "AI-Powered Chronic Kidney Disease Detection Report"
  );

  // Report meta bar: Report ID / Generated Date & Time / Version
  pdf.setDrawColor(210);
  pdf.setFillColor(238, 242, 247);
  pdf.roundedRect(20, 38, 170, 12, 2, 2, "FD");

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(90, 90, 90);
  pdf.text("REPORT ID", 25, 43.5);
  pdf.text("GENERATED", 90, 43.5);
  pdf.text("VERSION", 160, 43.5);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9.5);
  pdf.setTextColor(30, 30, 30);
  pdf.text(reportId, 25, 48.5);
  pdf.text(generatedAt, 90, 48.5);
  pdf.text("1.0", 160, 48.5);
  pdf.setTextColor(0, 0, 0);

  // Patient Information card
  drawCard(pdf, 20, 68, 170, 34, "Patient Information");
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(`Name : ${patient.name}`, 25, 85);
  pdf.text(`Age : ${patient.age}`, 25, 92);
  pdf.text(`Gender : ${patient.gender}`, 25, 99);

  // Clinical Parameters card
  drawCard(pdf, 20, 120, 170, 48, "Clinical Parameters");
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(`Blood Pressure : ${patient.bloodPressure} mmHg`, 25, 137);
  pdf.text(`Creatinine : ${patient.creatinine} mg/dL`, 110, 137);
  pdf.text(`Hemoglobin : ${patient.hemoglobin} g/dL`, 25, 145);
  pdf.text(`Albumin : ${patient.albumin} g/dL`, 110, 145);
  pdf.text(`Sugar : ${patient.sugar} mg/dL`, 25, 153);

  // Prediction Summary — highlighted colored box
  pdf.setDrawColor(...statusColor);
  pdf.setFillColor(...statusBg);
  pdf.roundedRect(20, 188, 170, 65, 3, 3, "FD");

  pdf.setFillColor(...statusColor);
  pdf.circle(28, 204, 3, "F");

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(15);
  pdf.setTextColor(...statusColor);
  pdf.text(statusLabel, 35, 206.5);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Confidence : ${result.confidence.toFixed(2)}%`, 25, 220);
  pdf.text(`Risk Level : ${riskLevel}`, 25, 228);
  pdf.text(`AI Model : ${AI_MODEL_NAME}`, 25, 236);

  drawFooter(pdf, "Page 1 of 2", false, generatedAt);

  // =========================================================================
  // PAGE 2 — AI Explanation, Recommendation, Images, Disclaimer
  // =========================================================================
  pdf.addPage();
  drawHeaderBanner(pdf, "AI Explanation", "How the prediction was made");

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  drawBulletLine(
    pdf,
    22,
    42,
    "The CNN model analyzed the uploaded CT scan for CKD-related patterns.",
    [21, 101, 192]
  );
  drawBulletLine(
    pdf,
    22,
    50,
    "Grad-CAM highlights the regions that most influenced the prediction.",
    [21, 101, 192]
  );
  drawBulletLine(
    pdf,
    22,
    58,
    "Explainable AI improves transparency and trust in the diagnosis.",
    [21, 101, 192]
  );

  // Result Summary card
  drawCard(pdf, 20, 72, 170, 36, "Result Summary");
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(`Prediction : ${statusLabel}`, 25, 89);
  pdf.text(`Confidence : ${result.confidence.toFixed(2)}%`, 25, 95);
  pdf.text(`Risk Level : ${riskLevel}`, 110, 89);
  pdf.text(`AI Model : ${AI_MODEL_NAME}`, 110, 95);

  // Recommendation card
  drawCard(pdf, 20, 122, 170, 36, "Recommendation");

  if (isCKD) {
    drawBulletLine(
      pdf,
      25,
      139,
      "CT findings suggest Chronic Kidney Disease.",
      [198, 40, 40]
    );
    drawBulletLine(
      pdf,
      25,
      146,
      "Consultation with a nephrologist is recommended.",
      [198, 40, 40]
    );
    drawBulletLine(
      pdf,
      25,
      153,
      "Perform further renal function tests.",
      [198, 40, 40]
    );
  } else {
    drawBulletLine(
      pdf,
      25,
      139,
      "No CT features suggestive of CKD.",
      [46, 125, 50]
    );
    drawBulletLine(
      pdf,
      25,
      146,
      "Continue regular health checkups.",
      [46, 125, 50]
    );
    drawBulletLine(
      pdf,
      25,
      153,
      "Clinical correlation is recommended.",
      [46, 125, 50]
    );
  }

  // Image section: equal size, centered, aligned, thin gray borders
  const IMG_Y = 172;
  const IMG_W = 75;
  const IMG_H = 50;
  const IMG_LEFT_X = 20;
  const IMG_RIGHT_X = 115; // 20 + 75 + 20mm gap = 115, right edge lands at 190 (page margin)

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(21, 101, 192);
  pdf.text("Original CT Scan", IMG_LEFT_X, IMG_Y - 4);
  pdf.text("Grad-CAM Heatmap", IMG_RIGHT_X, IMG_Y - 4);
  pdf.setTextColor(0, 0, 0);

  try {
    if (image) {
      const original = await imageToDataURL(image);
      pdf.setDrawColor(190);
      pdf.rect(IMG_LEFT_X, IMG_Y, IMG_W, IMG_H); // thin gray border
      pdf.addImage(
        original,
        "PNG",
        IMG_LEFT_X + 1.5,
        IMG_Y + 1.5,
        IMG_W - 3,
        IMG_H - 3
      );
    }

    if (gradcam) {
      const heatmap = await imageToDataURL(gradcam);
      pdf.setDrawColor(190);
      pdf.rect(IMG_RIGHT_X, IMG_Y, IMG_W, IMG_H); // thin gray border
      pdf.addImage(
        heatmap,
        "PNG",
        IMG_RIGHT_X + 1.5,
        IMG_Y + 1.5,
        IMG_W - 3,
        IMG_H - 3
      );
    } else {
      console.log("GradCAM missing");
    }
  } catch (err) {
    console.error("PDF IMAGE ERROR:", err);
  }

  // Medical Disclaimer card
  const DISCLAIMER_Y = IMG_Y + IMG_H + 14; // 14mm gap below images
  drawCard(pdf, 20, DISCLAIMER_Y, 170, 26, "Medical Disclaimer");
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text(
    "This report is generated using NephroScan AI for educational and",
    25,
    DISCLAIMER_Y + 16
  );
  pdf.text(
    "research purposes. It is not intended to replace professional",
    25,
    DISCLAIMER_Y + 21.5
  );
  pdf.text("medical diagnosis or clinical judgement.", 25, DISCLAIMER_Y + 27);

  drawFooter(pdf, "Page 2 of 2", true, generatedAt);

  // Sanitize the filename so the download always ends in .pdf, even if a
  // caller passes a name with no extension or the wrong one (e.g. ".jpg")
  let finalName = fileName || `${patient.name}_CKD_Report.pdf`;
  finalName = finalName.replace(/\.(jpg|jpeg|png|webp)$/i, "");
  if (!/\.pdf$/i.test(finalName)) {
    finalName += ".pdf";
  }

  pdf.save(finalName);
};